version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.rajiproject.integrations:HelloWorld
  packages:
  - name: EdgeRAJIProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
packages:
- name: EdgeRAJIProject
  gitServerName: RAJIRepo
  gitUrl: https://github.com/rasher20/EdgeRAJIProject
  gitUsername: rasher20
  gitToken: edge.scaffolding.EdgeRAJIProject.RAJIRepo.gitToken
  gitBranch: main
